# Generated by Django 5.2.15 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_remove_kbchunk_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kbdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "入库中"),
                    ("ready", "已入库"),
                    ("failed", "解析失败"),
                    ("unsupported", "不支持"),
                ],
                default="ready",
                max_length=16,
            ),
        ),
    ]
