# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_alter_kbdocument_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_type", models.CharField(choices=[("overview", "总览"), ("source", "来源页")], max_length=16)),
                ("slug", models.SlugField(max_length=160)),
                ("title", models.CharField(max_length=512)),
                ("content", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "已生成"), ("failed", "生成失败"), ("stale", "已过期")],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_pages",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wiki_pages",
                        to="knowledge.kbdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["page_type", "title"],
                "indexes": [
                    models.Index(fields=["kb", "page_type", "status"], name="knowledge_w_kb_id_5e175b_idx"),
                    models.Index(fields=["source_document", "page_type"], name="knowledge_w_source_f3f75c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WikiBuildJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "job_type",
                    models.CharField(choices=[("full", "全量刷新"), ("document", "文档刷新")], default="full", max_length=16),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "运行中"), ("success", "成功"), ("failed", "失败")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge.kbdocument",
                    ),
                ),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_build_jobs",
                        to="knowledge.knowledgebase",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["kb", "status", "-started_at"], name="knowledge_w_kb_id_ea64ad_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WikiLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_title", models.CharField(max_length=512)),
                ("link_type", models.CharField(default="wikilink", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="knowledge.wikipage",
                    ),
                ),
                (
                    "target_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_links",
                        to="knowledge.wikipage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source_page", "link_type"], name="knowledge_w_source_2d6eba_idx"),
                    models.Index(fields=["target_page"], name="knowledge_w_target_8305fe_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="wikipage",
            constraint=models.UniqueConstraint(fields=("kb", "slug"), name="knowledge_wikipage_kb_slug_uniq"),
        ),
    ]
