# Generated by Django 5.2.15 on 2026-06-10 07:28

import django.db.models.deletion
import drive.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=128)),
                ('original_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('file', models.FileField(upload_to=drive.models.stored_file_path)),
                ('ref_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_folder', models.BooleanField(default=False)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='drive.userfile')),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_files', to='drive.storedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_folder', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=128)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('chunk_size', models.PositiveBigIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('received_chunks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', '待上传'), ('uploading', '上传中'), ('merged', '已合并'), ('failed', '失败')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drive.storedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drive.userfile')),
            ],
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['owner', 'content_hash'], name='drive_store_owner_i_ad7d11_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['user', 'parent', 'is_deleted'], name='drive_userf_user_id_5c88d3_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['user', 'name'], name='drive_userf_user_id_31392c_idx'),
        ),
    ]
