# Generated by Django 5.2.15 on 2026-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0020_session_event_trajectory"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelusage",
            name="reasoning_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
