# Generated by Django 5.2.15 on 2026-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0021_model_usage_reasoning_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="context_window",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
