# Generated by Django 5.2.15 on 2026-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_knowledge_base", "0022_modelconfig_context_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelusage",
            name="request_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
