# Generated by Django 5.2.15 on 2026-06-10 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('chat', 'AI聊天'), ('pan', '网盘智答'), ('doc', '文档助手'), ('answer', '统一问答'), ('kb', '知识库')], default='chat', max_length=16)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'agent_type', 'created_at'], name='assistant_c_user_id_79dc8c_idx')],
            },
        ),
    ]
