# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("chat", "AI聊天"),
                    ("pan", "网盘智答"),
                    ("doc", "文档助手"),
                    ("answer", "统一问答"),
                    ("kb", "知识库"),
                ],
                default="chat",
                max_length=16,
            ),
        ),
    ]
