# Generated by Django 5.2.15

from django.db import migrations, models


def unify_assistant_messages(apps, schema_editor):
    ChatMessage = apps.get_model("assistant", "ChatMessage")
    ChatMessage.objects.filter(agent_type__in=["doc", "answer"]).delete()
    for message in ChatMessage.objects.exclude(agent_type="assistant").iterator():
        metadata = dict(message.metadata or {})
        metadata.setdefault("legacy_agent_type", message.agent_type)
        message.agent_type = "assistant"
        message.metadata = metadata
        message.save(update_fields=["agent_type", "metadata"])


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_remove_rewrite_agent_choice"),
    ]

    operations = [
        migrations.RunPython(unify_assistant_messages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chatmessage",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("assistant", "AI助手"),
                ],
                default="assistant",
                max_length=16,
            ),
        ),
    ]
