# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_unify_assistant_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agent_name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "运行中"), ("success", "成功"), ("failed", "失败")],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_runs",
                        to="assistant.agentrun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["user", "-started_at"], name="assistant_a_user_id_863df0_idx"),
                    models.Index(fields=["parent_run", "agent_name"], name="assistant_a_parent_0a4e40_idx"),
                    models.Index(fields=["agent_name", "status"], name="assistant_a_agent_n_6e9639_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="assistant.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["run", "created_at"], name="assistant_a_run_id_c186b3_idx"),
                    models.Index(fields=["event_type", "created_at"], name="assistant_a_event_t_ed5380_idx"),
                ],
            },
        ),
    ]
