# Generated by Codex on 2026-06-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_messages(apps, schema_editor):
    ChatMessage = apps.get_model("assistant", "ChatMessage")
    Conversation = apps.get_model("assistant", "Conversation")

    user_ids = (
        ChatMessage.objects.filter(conversation__isnull=True)
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids:
        conversation = Conversation.objects.create(user_id=user_id, title="历史对话")
        ChatMessage.objects.filter(user_id=user_id, conversation__isnull=True).update(conversation=conversation)


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0004_agent_run_event"),
        ("knowledge", "0004_wiki_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="新对话", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "活跃"), ("archived", "已归档")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("default_use_drive", models.BooleanField(default=False)),
                ("checkpoint", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_kb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_conversations",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "last_checkpoint_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assistant.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status", "-updated_at"], name="assistant_c_user_id_4de3d4_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="assistant.conversation",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["conversation", "created_at"], name="assistant_c_convers_2fcd8e_idx"),
        ),
        migrations.CreateModel(
            name="ConversationMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.CharField(
                        choices=[("user", "用户记忆"), ("kb", "知识库记忆")],
                        default="user",
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("fact", "事实"), ("preference", "偏好"), ("decision", "决策"), ("task", "任务")],
                        default="fact",
                        max_length=24,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("archived", "已归档")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kb",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_memories",
                        to="knowledge.knowledgebase",
                    ),
                ),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_items",
                        to="assistant.conversation",
                    ),
                ),
                (
                    "source_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memory_items",
                        to="assistant.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "scope", "status", "-updated_at"], name="assistant_c_user_id_692651_idx"),
                    models.Index(fields=["kb", "status", "-updated_at"], name="assistant_c_kb_id_279e76_idx"),
                    models.Index(fields=["content_hash"], name="assistant_c_content_7d07ba_idx"),
                ],
            },
        ),
        migrations.RunPython(migrate_existing_messages, migrations.RunPython.noop),
        migrations.RunSQL(
            """
            CREATE VIRTUAL TABLE IF NOT EXISTS assistant_conversation_memory_fts
            USING fts5(title, kind, scope, content, tokenize='trigram')
            """,
            reverse_sql="DROP TABLE IF EXISTS assistant_conversation_memory_fts",
        ),
    ]
